### ISSUE TITLE
Walk Overhaul incompatibility

### ISSUE THREAD

**Issue by DragonbornLevent** [Origins-Eternity/Sanity-Prequel#5]
When Sanity mod tries to disable sprinting (when sanity level is very low) it crashes with Walk Overhaul.

https://www.curseforge.com/minecraft/mc-mods/walk-overhaul

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (!mixinbooter-10.2.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/14/24 5:50 AM
Description: Ticking player

java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to com.walkoverhaul.IStamina
	at net.minecraft.entity.EntityLivingBase.handler$zzd000$walkoverhaul$setSprinting(EntityLivingBase.java:3105)
	at net.minecraft.entity.EntityLivingBase.func_70031_b(EntityLivingBase.java:1677)
	at com.origins_eternity.sanity.utils.Utils.checkStatus(Utils.java:110)
	at com.origins_eternity.sanity.event.CommonEvent.onPlayerTick(CommonEvent.java:128)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_CommonEvent_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

No Mixin Metadata is found in the Stacktrace.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.EntityLivingBase.handler$zzd000$walkoverhaul$setSprinting(EntityLivingBase.java:3105)
	at net.minecraft.entity.EntityLivingBase.func_70031_b(EntityLivingBase.java:1677)
	at com.origins_eternity.sanity.utils.Utils.checkStatus(Utils.java:110)
	at com.origins_eternity.sanity.event.CommonEvent.onPlayerTick(CommonEvent.java:128)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_CommonEvent_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 29
	Entity Name: L
	Entity's Exact location: -786.70, 1.00, -1279.64
	Entity's Block location: World: (-787,1,-1280), Chunk: (at 13,0,0 in -50,-80; contains blocks -800,0,-1280 to -785,255,-1265), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@16dbb431
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_431, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1356697480 bytes (1293 MB) / 1711276032 bytes (1632 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version      | Source                           | Signature                                |
	|:------ |:------------ |:------------ |:-------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft    | 1.12.2       | minecraft.jar                    | None                                     |
	| LCHIJA | mcp          | 9.42         | minecraft.jar                    | None                                     |
	| LCHIJA | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge        | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mixinbooter  | 10.2         | minecraft.jar                    | None                                     |
	| LCHIJA | jei          | 4.26.2       | HadEnoughItems_1.12.2-4.26.2.jar | None                                     |
	| LCHIJA | sanity       | 1.1.0        | sanity-1.1.0.jar                 | None                                     |
	| LCHIJA | walkoverhaul | 1.12.2-1.0   | walkoverhaul-1.12.2-1.1.jar      | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-10.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['L'/29, l='New World', x=-786.70, y=1.00, z=-1279.64]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Origins-Eternity** [comment]
Fixed in [a9e69fb](https://github.com/Origins-Eternity/Sanity-Prequel/commit/a9e69fb15edc21c0cf71fe1ad77a62c458d1f4bf)
